POST http://127.0.0.1:8080/api/promo/create
Accept: application/json
Content-type: application/json
#Cookie: PHPSESSID=

{
  "title": "new test title!",
  "mainText": "main test text",
  "category": "category"
}
###